package no.minecraft.Minecraftno.handlers.enums;

public enum MinecraftnoLog {
    BANKINN, BANKUT, BANKTRANSFER, KICK, BAN, GIVE, SETWARP, DELWARP, CHAT, MELDING, PURCHASE, ILLEGAL, TRADECHAT, SETBY, SETTETTSTED, SETPOI, UNBAN, WEEKBAN, SANDTAKFILL, SANDTAKNEW, SANDTAKDELETE
}